# Generated by Django 4.1.6 on 2023-03-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scheduler_owner', models.CharField(max_length=32)),
                ('Scheduler_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_owner_user', models.IntegerField(blank=True, default='', null=True)),
                ('Task_owner_scheduler', models.IntegerField(blank=True, default='', null=True)),
                ('Task_name', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('Task_description', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('Task_start_time', models.DateTimeField(blank=True, default='', null=True)),
                ('Task_end_time', models.DateTimeField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
